export const scenesFromFile = [
  {
    sceneID: 0,
    scene: "start",
    background: "src/assets/talky_talky_startscreen.png",
    question: "",
    avatar: "src/assets/start_model.png",
    text: "Talky-Talky",
    backgroundSize: "",
    option1: "",
    goToQuestionSceneIDOption1: null,
    pointOption1: null,
    option2: "",
    goToQuestionSceneIDOption2: null,
    pointOption2: null,
    customeBackScene: null,
  },
  {
    sceneID: 1,
    scene: "employee",
    background: "src/assets/employee_background.png",
    question: "",
    avatar: "src/assets/micperson.png",
    text: "Hi sir! How can I help you today?",
    backgroundSize: 963,
    option1: "",
    goToQuestionSceneIDOption1: null,
    pointOption1: null,
    option2: "",
    goToQuestionSceneIDOption2: null,
    pointOption2: null,
    customeBackScene: null,
  },
  {
    sceneID: 2,
    scene: "customer",
    background: "src/assets/third_scene_backgorund.png",
    question: "",
    avatar: "src/assets/customer_third.png",
    text: "I would like to move my reservations to a new date",
    backgroundSize: 1203,
    option1: "",
    goToQuestionSceneIDOption1: null,
    pointOption1: null,
    option2: "",
    goToQuestionSceneIDOption2: null,
    pointOption2: null,
    customeBackScene: null,
  },
  {
    sceneID: 3,
    scene: "employee",
    background: "src/assets/employee_background.png",
    question: "",
    avatar: "src/assets/micperson.png",
    text: "The line is really long right now so it will take awhile",
    backgroundSize: 963,
    option1: "",
    goToQuestionSceneIDOption1: null,
    pointOption1: null,
    option2: "",
    goToQuestionSceneIDOption2: null,
    pointOption2: null,
    customeBackScene: null,
  },
  {
    sceneID: 4,
    scene: "question",
    background: "src/assets/employee_background.png",
    question:
      "You know he will have to wait in a long line, what would you say to him?",
    backgroundSize: 963,
    option1: "Let him wait without saying anything",
    goToQuestionSceneIDOption1: 5,
    pointOption1: 0.5,
    option2:
      "Tell him that the line might be long, if its not urgent. He can try calling after 1 hour",
    goToQuestionSceneIDOption2: 6,
    pointOption2: 1,
    customeBackScene: null,
  },
  {
    sceneID: 5,
    scene: "customer",
    background: "src/assets/third_scene_backgorund.png",
    question: "",
    avatar: "src/assets/customer_third.png",
    text: "Its more than 5 minutes. Let me call them again in an hour",
    backgroundSize: 1263,
    option1: "",
    goToQuestionSceneIDOption1: null,
    pointOption1: null,
    option2: "",
    goToQuestionSceneIDOption2: null,
    pointOption2: null,
    customeBackScene: 4,
  },
  {
    sceneID: 6,
    scene: "customer",
    background: "src/assets/third_scene_backgorund.png",
    question: "",
    avatar: "src/assets/fifth_model.png",
    text: "I have waited for so long! I need to call them again!",
    backgroundSize: 1263,
    option1: "",
    goToQuestionSceneIDOption1: null,
    pointOption1: null,
    option2: "",
    goToQuestionSceneIDOption2: null,
    pointOption2: null,
    customeBackScene: 4,
  },
  {
    sceneID: 7,
    scene: "time",
    question: "",
    background: "src/assets/third_scene_backgorund.png",
    text: "1 Hour Later",
    backgroundSize: 1263,
    option1: "",
    goToQuestionSceneIDOption1: null,
    pointOption1: null,
    option2: "",
    goToQuestionSceneIDOption2: null,
    pointOption2: null,
    customeBackScene: 4,
  },
  {
    sceneID: 8,
    scene: "employee",
    background: "src/assets/employee_background.png",
    question: "",
    avatar: "src/assets/micperson.png",
    text: "Hello Sir! How can I help you?",
    backgroundSize: 963,
    option1: "",
    goToQuestionSceneIDOption1: null,
    pointOption1: null,
    option2: "",
    goToQuestionSceneIDOption2: null,
    pointOption2: null,
    customeBackScene: null,
  },
  {
    sceneID: 9,
    scene: "customer",
    background: "src/assets/third_scene_backgorund.png",
    question: "",
    avatar: "src/assets/customer_third.png",
    text: "Hi, I would like to request a change in my reservation's date",
    backgroundSize: 1203,
    option1: "",
    goToQuestionSceneIDOption1: null,
    pointOption1: null,
    option2: "",
    goToQuestionSceneIDOption2: null,
    pointOption2: null,
    customeBackScene: null,
  },
  {
    sceneID: 10,
    scene: "customer",
    background: "src/assets/third_scene_backgorund.png",
    question: "",
    avatar: "src/assets/customer_third.png",
    text: "If possible, can I move my reservation date to the 15th of Feb?",
    backgroundSize: 1203,
    option1: "",
    goToQuestionSceneIDOption1: null,
    pointOption1: null,
    option2: "",
    goToQuestionSceneIDOption2: null,
    pointOption2: null,
    customeBackScene: null,
  },
  {
    sceneID: 11,
    scene: "employee",
    background: "src/assets/employee_background.png",
    question: "",
    avatar: "src/assets/micperson.png",
    text: "That is possible but there will be a fee for changing date of reservation",
    backgroundSize: 963,
    option1: "",
    goToQuestionSceneIDOption1: null,
    pointOption1: null,
    option2: "",
    goToQuestionSceneIDOption2: null,
    pointOption2: null,
    customeBackScene: null,
  },
  {
    sceneID: 12,
    scene: "customer",
    background: "src/assets/third_scene_backgorund.png",
    question: "",
    avatar: "src/assets/fifth_model.png",
    text: "What? I thought there were not fees for changing",
    backgroundSize: 1263,
    option1: "",
    goToQuestionSceneIDOption1: null,
    pointOption1: null,
    option2: "",
    goToQuestionSceneIDOption2: null,
    pointOption2: null,
    customeBackScene: null,
  },
  {
    sceneID: 12,
    scene: "employee",
    background: "src/assets/employee_background.png",
    question: "",
    avatar: "src/assets/micperson.png",
    text: "I'm sorry but if you change 3 days prior, we will charge a fee sir.",
    backgroundSize: 963,
    option1: "",
    goToQuestionSceneIDOption1: null,
    pointOption1: null,
    option2: "",
    goToQuestionSceneIDOption2: null,
    pointOption2: null,
    customeBackScene: null,
  },
  {
    sceneID: 13,
    scene: "question",
    background: "src/assets/employee_background.png",
    question:
      "The customer is complaining, what should you do in this situation?",
    option1:
      "Apologize and tell him that they will make it clear on the website in the future",
    goToQuestionSceneIDOption1: 5,
    pointOption1: 0.5,
    option2:
      "Apologize to him and suggest a new promotion that comes with the bookings",
    goToQuestionSceneIDOption2: 6,
    pointOption2: 1,
    backgroundSize: 963,
    customeBackScene: null,
  },
  {
    sceneID: 14,
    scene: "employee",
    background: "src/assets/employee_background.png",
    question: "",
    avatar: "src/assets/micperson.png",
    text: "We're really sorry about this, we will make it more clear on the website!",
    backgroundSize: 963,
    option1: "",
    goToQuestionSceneIDOption1: null,
    pointOption1: null,
    option2: "",
    goToQuestionSceneIDOption2: null,
    pointOption2: null,
    customeBackScene: null,
  },
  {
    sceneID: 15,
    scene: "customer",
    background: "src/assets/third_scene_backgorund.png",
    question: "",
    avatar: "src/assets/customer_third.png",
    text: "Okay! then can I change to 14th of Feb? That has no fees right?",
    backgroundSize: 1203,
    option1: "",
    goToQuestionSceneIDOption1: null,
    pointOption1: null,
    option2: "",
    goToQuestionSceneIDOption2: null,
    pointOption2: null,
    customeBackScene: null,
  },
  {
    sceneID: 16,
    scene: "question",
    background: "src/assets/employee_background.png",
    question: "The customer is louder and has more energy, what would you do?",
    option1: "Stay Calm and control the tone",
    goToQuestionSceneIDOption1: 5,
    pointOption1: 0.5,
    option2: "Be adaptable and match the energy of the customer",
    goToQuestionSceneIDOption2: 6,
    pointOption2: 1,
    backgroundSize: 963,
    customeBackScene: null,
  },
  {
    sceneID: 17,
    scene: "employee",
    background: "src/assets/employee_background.png",
    question: "",
    avatar: "src/assets/micperson.png",
    text: "Yes, that would incur no extra fees. Would you like to proceed?",
    backgroundSize: 963,
    option1: "",
    goToQuestionSceneIDOption1: null,
    pointOption1: null,
    option2: "",
    goToQuestionSceneIDOption2: null,
    pointOption2: null,
    customeBackScene: null,
  },
  {
    sceneID: 18,
    scene: "customer",
    background: "src/assets/third_scene_backgorund.png",
    question: "",
    avatar: "src/assets/customer_third.png",
    text: "Yes, I would like to proceed with that option!",
    backgroundSize: 1203,
    option1: "",
    goToQuestionSceneIDOption1: null,
    pointOption1: null,
    option2: "",
    goToQuestionSceneIDOption2: null,
    pointOption2: null,
    customeBackScene: null,
  },
  {
    sceneID: 19,
    scene: "employee",
    background: "src/assets/employee_background.png",
    question: "",
    avatar: "src/assets/micperson.png",
    text: "Okay, your reservations has been changed. ",
    backgroundSize: 963,
    option1: "",
    goToQuestionSceneIDOption1: null,
    pointOption1: null,
    option2: "",
    goToQuestionSceneIDOption2: null,
    pointOption2: null,
    customeBackScene: null,
  },
  {
    sceneID: 20,
    scene: "question",
    background: "src/assets/employee_background.png",
    question: "The problem has been solve. What will you do next?",
    option1: "Ask if there is anything else he needs?",
    goToQuestionSceneIDOption1: 21,
    pointOption1: 1,
    option2:
      "Just tell him the change is done and say Thank you for using their service",
    goToQuestionSceneIDOption2: 21,
    pointOption2: 0.5,
    backgroundSize: 963,
    customeBackScene: null,
  },
  {
    sceneID: 21,
    scene: "customer",
    background: "src/assets/third_scene_backgorund.png",
    question: "",
    avatar: "src/assets/customer_third.png",
    text: "That is it now, Thank you so much!",
    backgroundSize: 1203,
    option1: "",
    goToQuestionSceneIDOption1: null,
    pointOption1: null,
    option2: "",
    goToQuestionSceneIDOption2: null,
    pointOption2: null,
    customeBackScene: null,
  },
];
